/* Lógico_1: */

CREATE TABLE ENDERECO (
    complemento varchar(50),
    cep varchar(9),
    logradouro varchar(100),
    id int PRIMARY KEY
);

CREATE TABLE PESSOA (
    senha varchar(25),
    id int PRIMARY KEY,
    nome varchar(100),
    telefone varchar(15),
    email varchar(100),
    cnpj varchar(18),
    cpf varchar(14),
    PESSOA_TIPO INT,
    matricula varchar(20),
    dataAdmissao date,
    dataDemissao date,
    cnh varchar(11),
    FK_CARGO_id int
);

CREATE TABLE ESTACIONAMENTO (
    latitude varchar(15),
    qntVagas int,
    valorHora numeric,
    nome varchar(100),
    id int PRIMARY KEY,
    longitude varchar(15),
    FK_PESSOA_id int,
    FK_ENDERECO_id int
);

CREATE TABLE CARGO (
    id int PRIMARY KEY,
    nome varchar(100)
);

CREATE TABLE PAGAMENTO_ESTACIONAMENTO (
    data date,
    valor numeric,
    id int PRIMARY KEY,
    FK_PESSOA_id int
);

CREATE TABLE VAGA (
    numero int,
    andar int,
    id int PRIMARY KEY,
    FK_ESTACIONAMENTO_id int
);

CREATE TABLE VEICULO (
    modelo varchar(30),
    ano int,
    placa varchar(8),
    marca varchar(50),
    id int PRIMARY KEY,
    FK_PESSOA_id int
);

CREATE TABLE FORMA_PAGAMENTO (
    id int,
    bandeira varchar(50),
    numero varchar(30),
    numParcelas int,
    conta varchar(50),
    FORMA_PAGAMENTO_TIPO INT,
    FK_TIPO_CARTAO_id int,
    FK_PAGAMENTO_ESTACIONAMENTO_id int,
    Campo_1 int,
    PRIMARY KEY (id, Campo_1)
);

CREATE TABLE TIPO_CARTAO (
    id int PRIMARY KEY,
    descricao varchar(7)
);

CREATE TABLE RESERVA (
    Id int PRIMARY KEY,
    horaReserva time,
    dataReserva date,
    horaSaida time,
    FK_PAGAMENTO_ESTACIONAMENTO_id int,
    FK_VAGA_id int,
    FK_VEICULO_id int,
    FK_PESSOA_id int
);

CREATE TABLE trabalha (
    FK_PESSOA_id int,
    FK_ESTACIONAMENTO_id int
);
 
ALTER TABLE PESSOA ADD CONSTRAINT FK_PESSOA_0
    FOREIGN KEY (FK_PESSOA_id)
    REFERENCES PESSOA (id);
 
ALTER TABLE PESSOA ADD CONSTRAINT FK_PESSOA_2
    FOREIGN KEY (FK_CARGO_id)
    REFERENCES CARGO (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE ESTACIONAMENTO ADD CONSTRAINT FK_ESTACIONAMENTO_1
    FOREIGN KEY (FK_PESSOA_id)
    REFERENCES PESSOA (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE ESTACIONAMENTO ADD CONSTRAINT FK_ESTACIONAMENTO_2
    FOREIGN KEY (FK_ENDERECO_id)
    REFERENCES ENDERECO (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PAGAMENTO_ESTACIONAMENTO ADD CONSTRAINT FK_PAGAMENTO_ESTACIONAMENTO_1
    FOREIGN KEY (FK_PESSOA_id)
    REFERENCES PESSOA (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE VAGA ADD CONSTRAINT FK_VAGA_1
    FOREIGN KEY (FK_ESTACIONAMENTO_id)
    REFERENCES ESTACIONAMENTO (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_1
    FOREIGN KEY (FK_PESSOA_id)
    REFERENCES PESSOA (id)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE FORMA_PAGAMENTO ADD CONSTRAINT FK_FORMA_PAGAMENTO_1
    FOREIGN KEY (FK_TIPO_CARTAO_id)
    REFERENCES TIPO_CARTAO (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE FORMA_PAGAMENTO ADD CONSTRAINT FK_FORMA_PAGAMENTO_2
    FOREIGN KEY (FK_PAGAMENTO_ESTACIONAMENTO_id)
    REFERENCES PAGAMENTO_ESTACIONAMENTO (id)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE FORMA_PAGAMENTO ADD CONSTRAINT FK_FORMA_PAGAMENTO_3
    FOREIGN KEY (Campo_1???)
    REFERENCES ??? (???);
 
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_1
    FOREIGN KEY (FK_PAGAMENTO_ESTACIONAMENTO_id)
    REFERENCES PAGAMENTO_ESTACIONAMENTO (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_2
    FOREIGN KEY (FK_VAGA_id)
    REFERENCES VAGA (id)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_3
    FOREIGN KEY (FK_VEICULO_id)
    REFERENCES VEICULO (id)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_4
    FOREIGN KEY (FK_PESSOA_id)
    REFERENCES PESSOA (id)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE trabalha ADD CONSTRAINT FK_trabalha_0
    FOREIGN KEY (FK_PESSOA_id)
    REFERENCES PESSOA (id)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE trabalha ADD CONSTRAINT FK_trabalha_1
    FOREIGN KEY (FK_ESTACIONAMENTO_id)
    REFERENCES ESTACIONAMENTO (id)
    ON DELETE SET NULL ON UPDATE CASCADE;